@hostname = http://127.0.0.1
@port = 5000
@host = {{hostname}}:{{port}}
# @host = https://meji-ng.herokuapp.com/
@Authorization = IjI1Zjc1NjRiN2NkMTQyYTY5MjlhMTMzZTkzODRlYzU2Ig.YFI30g.yNCajtuI6kwYj65OiHT5KGsxya0


#Create
post  {{host}}/user HTTP/1.1
content-type: application/json

{
    "name": "oodsoo",
    "username": "wwww",
    "email" : "wwww@wwwww.com",
    "phone" : "ozxzxzxoooO",
    "password": "1Qqqqqqq",
    "confirm_url": "example.com/confirm",
    "confirm_email": "<a href='{0}'> Click here </a>"
}
###

#Fix
get  {{host}}/fix HTTP/1.1
content-type: application/json
Authorization: {{Authorization}}

###

#test
get  {{host}}/customer_view/da24bca444bb43e78bd9882b23ecb29e/52ca93a7965741ff8576c6f7bc52d3fd HTTP/1.1
content-type: application/json
# Authorization: {{Authorization}}

###