MAIL_DEFAULT_SENDER = ("Meji", "meji.hello@gmail.com")
MAIL_SERVER = 'in-v3.mailjet.com'
MAIL_PORT = 587
MAIL_USE_TSL = True

EMAIL_CONFIRM_EXP = 3600

# LOGIN_LOCK_DURATION = 120
# LOGIN_LOCK_ATTEMPT = 3
